from fastapi import APIRouter, Depends, Header, HTTPException
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.database import get_db
from app.models import Suggestion, Incident, Task
from app.schemas.suggestion import SuggestionResponse, SuggestionUpdate
from app.services.suggestion_engine import generate_suggestions
from app.services.timeline_service import log_event

router = APIRouter(
    prefix="/api/v1/incidents/{incident_id}/suggestions", tags=["suggestions"]
)

ROLE_TASK_TYPE_MAP = {
    "itsec": "report",
    "dpo": "assessment",
    "legal": "assessment",
    "ciso": "notification",
    "communications": "general",
    "compliance": "review",
    "sysadmin": "info_request",
}


@router.get("/", response_model=list[SuggestionResponse])
async def list_suggestions(
    incident_id: int,
    db: AsyncSession = Depends(get_db),
):
    result = await db.execute(
        select(Suggestion)
        .where(Suggestion.incident_id == incident_id)
        .order_by(Suggestion.created_at.desc())
    )
    return result.scalars().all()


@router.post("/generate", response_model=list[SuggestionResponse])
async def trigger_generate(
    incident_id: int,
    x_role: str = Header(default="iso"),
    db: AsyncSession = Depends(get_db),
):
    incident = await db.get(Incident, incident_id)
    if not incident:
        raise HTTPException(404, "Incident not found")

    created = await generate_suggestions(db, incident_id)

    await log_event(
        db,
        incident_id,
        "suggestions_generated",
        f"{len(created)} suggestions generated by {x_role}",
        x_role,
    )

    return created


@router.patch("/{suggestion_id}", response_model=SuggestionResponse)
async def update_suggestion(
    incident_id: int,
    suggestion_id: int,
    data: SuggestionUpdate,
    x_role: str = Header(default="iso"),
    db: AsyncSession = Depends(get_db),
):
    sug = await db.get(Suggestion, suggestion_id)
    if not sug or sug.incident_id != incident_id:
        raise HTTPException(404, "Suggestion not found")

    old_status = sug.status
    if data.title is not None:
        sug.title = data.title
    if data.description is not None:
        sug.description = data.description
    if data.target_role is not None:
        sug.target_role = data.target_role
    if data.priority is not None:
        sug.priority = data.priority
    if data.task_type is not None:
        sug.task_type = data.task_type
    if data.status is not None:
        sug.status = data.status

    if data.status == "dispatched" and sug.target_role:
        description = sug.description or ""
        task_type = sug.task_type or ROLE_TASK_TYPE_MAP.get(sug.target_role, "general")

        task = Task(
            incident_id=incident_id,
            title=sug.title,
            description=description,
            assigned_to_role=sug.target_role,
            created_by_role=x_role,
            task_type=task_type,
            priority=sug.priority or "medium",
            status="pending",
        )
        db.add(task)

    event_description = f"Task draft '{sug.title}' updated"
    if data.status is not None:
        event_description = f"Task draft '{sug.title}' status: {old_status} -> {data.status}"

    await log_event(db, incident_id, "suggestion_updated", event_description, x_role)

    await db.commit()
    await db.refresh(sug)
    return sug
