from fastapi import APIRouter, Depends, Header, HTTPException
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.database import get_db
from app.models import Suggestion, Incident, Task
from app.schemas.suggestion import SuggestionResponse, SuggestionUpdate
from app.services.suggestion_engine import generate_suggestions
from app.services.timeline_service import log_event
from app.services.legal_summary_service import generate_legal_summary

router = APIRouter(
    prefix="/api/v1/incidents/{incident_id}/suggestions", tags=["suggestions"]
)

ROLE_TASK_TYPE_MAP = {
    "itsec": "report",
    "dpo": "assessment",
    "legal": "assessment",
    "ciso": "notification",
    "communications": "general",
    "compliance": "review",
    "sysadmin": "info_request",
}


@router.get("/", response_model=list[SuggestionResponse])
async def list_suggestions(
    incident_id: int,
    db: AsyncSession = Depends(get_db),
):
    result = await db.execute(
        select(Suggestion)
        .where(Suggestion.incident_id == incident_id)
        .order_by(Suggestion.created_at.desc())
    )
    return result.scalars().all()


@router.post("/generate", response_model=list[SuggestionResponse])
async def trigger_generate(
    incident_id: int,
    x_role: str = Header(default="iso"),
    db: AsyncSession = Depends(get_db),
):
    incident = await db.get(Incident, incident_id)
    if not incident:
        raise HTTPException(404, "Incident not found")

    created = await generate_suggestions(db, incident_id)

    await log_event(
        db,
        incident_id,
        "suggestions_generated",
        f"{len(created)} suggestions generated by {x_role}",
        x_role,
    )

    return created


@router.patch("/{suggestion_id}", response_model=SuggestionResponse)
async def update_suggestion(
    incident_id: int,
    suggestion_id: int,
    data: SuggestionUpdate,
    x_role: str = Header(default="iso"),
    db: AsyncSession = Depends(get_db),
):
    sug = await db.get(Suggestion, suggestion_id)
    if not sug or sug.incident_id != incident_id:
        raise HTTPException(404, "Suggestion not found")

    old_status = sug.status
    sug.status = data.status

    if data.status == "dispatched" and sug.target_role:
        description = sug.description or ""
        task_type = sug.task_type or ROLE_TASK_TYPE_MAP.get(sug.target_role, "general")

        if sug.target_role == "legal" and task_type == "assessment":
            try:
                summary = await generate_legal_summary(db, incident_id)
                if summary:
                    description = (description + "\n\n" if description else "") + "---\n\n**Auto-generated legal briefing:**\n\n" + summary
            except Exception:
                pass

        task = Task(
            incident_id=incident_id,
            title=sug.title,
            description=description,
            assigned_to_role=sug.target_role,
            created_by_role=x_role,
            task_type=task_type,
            priority=sug.priority or "medium",
            status="pending",
        )
        db.add(task)

    await log_event(
        db,
        incident_id,
        "suggestion_updated",
        f"Suggestion '{sug.title}' status: {old_status} -> {data.status}",
        x_role,
    )

    await db.commit()
    await db.refresh(sug)
    return sug
